# Improved Comment Detection Logic
# Generated by debug_comments.py


# IMPROVED COMMENT DETECTION - Add this to person.py get_comments method

# Try multiple selectors in order of preference
comment_selectors = [
    "[data-urn*='comment']",
    ".feed-shared-update-v2",
    ".feed-shared-comment",
    "article[data-urn]",
    "[data-test-id*='comment']",
    ".activity-item",
    ".feed-shared-mini-update-v2"
]

comment_elements = []
for selector in comment_selectors:
    try:
        elements = self.driver.find_elements(By.CSS_SELECTOR, selector)
        if elements:
            print(f"✅ Found {len(elements)} elements with selector: {selector}")
            comment_elements = elements
            break
        else:
            print(f"❌ No elements found with selector: {selector}")
    except Exception as e:
        print(f"⚠️  Error with selector {selector}: {e}")
        continue

if not comment_elements:
    print("🔍 No comment elements found with any selector. Checking page content...")
    try:
        page_source = self.driver.page_source
        if "No activity yet" in page_source or "hasn't shared anything" in page_source:
            print("📝 Profile has no recent activity")
        elif "comment" in page_source.lower():
            print("📝 Page contains 'comment' text but elements not found")
        else:
            print("📝 Page loaded but structure unclear")
    except Exception as e:
        print(f"Error checking page source: {e}")
